# Generated by Django 2.1.7 on 2019-07-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='boo_reviews',
            new_name='book_reviews',
        ),
    ]
