# Generated by Django 2.1.7 on 2019-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190711_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_reviews',
        ),
    ]
