# Generated by Django 2.1.7 on 2019-07-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_book_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_reviews',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='main.Post'),
        ),
    ]
